### PR TITLE
Changed レポジトリ to リポジトリ for consistency

### PR DESCRIPTION
**Pull request by rikutakei**
Just a small change to make the spelling consistent for the previously translated part of the document

### CODE REVIEW

**Review by TomKellyGenetics — APPROVED** [review]
I'm okay to merge this quickly as it's a small change.

**Comment by TomKellyGenetics** [comment]
Have you checked if it's misspelled anywhere else like the wiki pages or other lessons?

**Comment by TomKellyGenetics** [comment]
Actually how about "[リポジトリー](https://jisho.org/search/%E3%83%AA%E3%83%9D%E3%82%B8%E3%83%88%E3%83%AA)" ?

**Comment by joelnitta** [comment]
I think リポジトリ (not リポジトリー) is more common (14 million vs 120,000 hits on google).
If you've caught it everywhere so far, I think we can merge this.

**Comment by TomKellyGenetics** [comment]
> I think リポジトリ (not リポジトリー) is more common (14 million vs 120,000 hits on google).
> If you've caught it everywhere so far, I think we can merge this.

Ok let's stick with this then (my suggestion is based on writing Kelly as ケリー). I've updated the other files to be consistent with it.

**Pull request merged**
