### PR TITLE
Shell lessons 1 and 2

### LINKED ISSUE #93: Translation: shell-novice Episode 1
Translation: shell-novice Episode 1 "Introducing the Shell" (01-intro.md)
-----

* Please [see the README for more information about editing PO files](https://github.com/swcarpentry-ja/i18n/blob/ja/README_en.md#about-po-files)
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----

* PO fileの編集については[READMEをご参照ください](https://github.com/swcarpentry-ja/i18n#about-po-files)。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/i18n/blob/f4aed5e805895a613b0cdffffefd0431a75ac54d/po/shell-novice.ja.po#L778-L1461

### LINKED ISSUE #94: Translation: shell-novice Episode 2
Translation: shell-novice Episode 2 "Navigating Files and Directories" (02-filedir.md)
-----

* Please [see the README for more information about editing PO files](https://github.com/swcarpentry-ja/i18n/blob/ja/README_en.md#about-po-files)
* Please assign yourself (or add a comment) to the issue **before** you start translating, so other people know that you are translating.
* Once you have finished translating, send a pull request and reference this issue.

-----

* PO fileの編集については[READMEをご参照ください](https://github.com/swcarpentry-ja/i18n#about-po-files)。
* あなたが翻訳し始めたと分かるように、翻訳を**始める前**にこのイシューを自分に割り振って(assign)、あるいはコメントを書いて下さい。
* 翻訳が終わったら、プルリクエストを開いて、このイシューを参照・リンクして下さい。

https://github.com/swcarpentry-ja/i18n/blob/f4aed5e805895a613b0cdffffefd0431a75ac54d/po/shell-novice.ja.po#L1462-L3419

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Reopens #153 

Closes #93 and #94

Originally submitted by @megane0-0

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
Sorry I tried to figure out how to transfer ownership of the PR to @megane0-0 but I cannot unless we close this PR and reopen one from his account. It shouldn't be too much trouble to handle reviews from my account though. I think anyone with write-access to the repository has suggestion commit powers actually.

**Comment by megane0-0** [comment]
What I need to do is close this PR and reopen it, right? I'll try.

**Comment by megane0-0** [comment]
re-open PR #173

**Comment by TomKellyGenetics** [comment]
Open via this link 👍  https://github.com/swcarpentry-ja/i18n/compare/ja...megane0-0:ja (click "Create Pull Request"). Sorry I should've explained this.

**Pull request closed without merging**
