### PR TITLE
migrate changes to lang.md to theme repo

### LINKED ISSUE #116: Problems with R-novice-gapminder table of contents and headers
There are several small things that need to be fixed in the latest rendered [R-novice-gapminder translation](https://swcarpentry-ja.github.io/r-novice-gapminder/ja/index/index.html).

In the table of contents:
- Lesson 5 title is in English
- Lesson 8 is empty
- Lesson 13 title is in in English
- The translation for "finish" as 仕上がり doesn't really make sense in this context (consider changing in [lang.md](https://github.com/swcarpentry-ja/i18n/blob/ja/lang.md)). Probably 終わり is better?

In the outline for each lesson, "Teaching" still shows up as　教えります (should be 講義, as set in `lang.md`)

### PR DESCRIPTION
**Pull request by TomKellyGenetics**
Removes `lang.md` and copies changes to `carp-theme` https://github.com/swcarpentry-ja/carp-theme/pull/1/files#diff-a8d0d24ca88dc90a93d0453656a2275a

https://github.com/swcarpentry-ja/carp-theme/pull/1

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
If this translation is okay, then we're good to merge this.

```diff
-msgstr "> ## Prerequisites"
+msgstr "> ## 前提条件"
```

Only other change is deleting file `lang.md` to avoid confusion with the `carp-theme/assets/i18n/ja.md` file.

**Comment by TomKellyGenetics** [comment]
As suggested by @masamiy. These have all been changed to a non-literal translation (background knowledge).

```diff
-msgstr "> ## 前提条件"
+msgstr "> ## 予備知識"
```

I've created a Wiki page [for lesson terminology](https://github.com/swcarpentry-ja/i18n/wiki/Glossary-for-Lesson-Terms) to keep track of changes like this.

**Review by joelnitta — APPROVED** [review]
Looks good to me! (Remember that `Prerequisites` should probably be in `ja.md` in the theme repo eventually)

**Comment by TomKellyGenetics** [comment]
Thanks for the reminder. I'll check if it's possible to add it to `carp-theme`.

**Pull request merged**
