### PR TITLE
add translation in background

### PR DESCRIPTION
**Pull request by megane0-0**
I closed the previous submission to the different place. Hope this is the right place.
#4760815

### CODE REVIEW

**Comment by TomKellyGenetics** [comment]
As submitted to https://github.com/swcarpentry-i18n/i18n/pull/13

**Comment by TomKellyGenetics** [comment]
This is the repo for Japanese but it's unclear what this is doing. Are you updating the submodule for the git-novice lessons? Please note there is an ongoing translation of the current version: #37 by @rikutakei 

We will keep the current submodule as an archive of the version that we're translating. @dpshelio has developed tools to sync updated sections with translations (https://github.com/swcarpentry-i18n/i18n) that we will test out to maintain updates. We will try this _after_ this version has been translated.

**Comment by rikutakei** [comment]
@TomKellyGenetics Agreed. What does this do? I'm not super familiar with git submodules and "ins-and-outs" of git itself, so if you could explain what this can do, it'll be super helpful.

`git-novice` is already included as a submodule at the root of this repo, and don't know if adding the same submodule to a sub-directory is going to improve anything.

**Comment by TomKellyGenetics** [comment]
I can explain in more details later but basically. Submodule loads another git repo inside this one. At the moment it’s the head of the English lessons when I added them. 

Messing with them will pull updates English lessons from the original repos. We need to do this to update but right now it will be confusing as it will create fresh English lessons that haven’t been translated. I think we can merge the new sections in English into the lessons to update translations (this was still in progress in the tools but we should be able to merge). David has told me he’s working on the tools again over the next few weekends so if could be improved soon. (Seems like the Spanish team are ready to test merging updates)

**Comment by joelnitta** [comment]
Closing this as the original PR seems to have been made in error

**Comment by TomKellyGenetics** [comment]
I think this was fixing some issues we had but I think they're dealt with now. As mentioned in #78, the git lesson was the first we used translation tools on so there were some issues with it.

**Pull request closed without merging**
