### PR TITLE
Translate shell-novice about REPL

### PR DESCRIPTION
**Pull request by manabuishii**

### CODE REVIEW

**Comment by rikutakei** [comment]
In this particular paragraph, I think the lesson is trying to explain *where* the main idea of REPL is coming from, by explaining what a REPL is on the way.
I think the current translation explains what a REPL is in a direct way, but feels like it hasn't been connected back to why it's called REPL.
Translation is alright, so if you could change the wording a bit so it emphasises *why* it's called REPL, I think it would be OK.


この箇所では、REPLの由来を、REPLの仕組みを細かく分解しながら説明しています。
翻訳された文章では、REPLの仕組みは解説されていますが、REPLの由来に結びついていない気がします。(line 901と902の間に何かしらの「つなぎ」がほしいです。)
Line902、もしくは909で、なぜREPLと呼ばれているのかに触れていただければいいと思います。
翻訳自体は間違ってはいないので、文体を少し見直していただければOKだと思います。


例えば：
>コマンドラインインターフェースの核は、REPL (read-evaluate-print-loop)と呼ばれています。
>これは、シェルにコマンドを入力し、Enter(または Return)キーを押した時に起こる動作:
>1. コマンドを読み込む (read)
>2. コマンドを実行する (または "評価する" - evaluate)
>3. 結果を出力する (print)

(line 909:) 
>そして、プロンプトで次のコマンドの入力を待ち、1〜3の動作を繰り返す・ループ(loop)することから、頭文字を取ってREPLと呼ばれています。

**Comment by rikutakei** [comment]
あと、この文章と：
>コマンドラインインターフェースの核は、REPL (read-evaluate-print-loop)と呼ばれています。

この文章：

>コマンドラインインターフェースの核では、REPL (read-evaluate-print-loop)が行われています。

どちらがいいと思いますか？

**Comment by TomKellyGenetics** [comment]
This does raise an issue that could come up again. Terminology like "REPL" is obvious (self-explanatory) for English-speakers but needs more explanation in a foreign language. Is it better to keep the full English term and explain the meaning of each word?

> REPL (read-evaluate-print-loop)と呼ばれています。
>  英語で読み込みはreadです。英語で評価はevaluateです。英語で出力はprintです。英語でループはloopです。

I know this might seem tedious but maybe notes like this to explain English terminology may be needed (similarly for concepts like "ls" for "list").

**Comment by rikutakei** [comment]
I think keeping the full English term is visually better (it's much clearer to see what words are making up the abbreviation in the first instance).
Translating word-by-word isn't very clean and likely not necessary either.

For example, in this particular paragraph, the components that make up REPL are explained on the way and therefore can be translated when it pops up, so there's no need for explicit word-by-word translation - this will be the case for most abbreviations/commands that will come up in any SWC material.

However, if this is **not** the case in any future section(s), it should be translated at the point where the word occurs, and also explain why and how it has been abbreviated.

For example, with your `ls` example:
>`ls`は "list" (一覧・目録)を略したコマンドで、ディレクトリの中身を見るためのコマンドです。

**Comment by TomKellyGenetics** [comment]
Yes. I think we have some freedom here depending on the case at hand but we should try to be consistent. What's important is to bear in mind why Japanese learners would need to understand the English terminology. I can think of these cases:

- This terminology is used in forums or help menus so it is important to understand
- It makes seemingly abstract terms and commands "REPL", "cd", "ls", etc easier to remember

Depending on the purpose here, we would need to decide whether keep it faithfully in English (romaji) or use katakana forms.

**Comment by rikutakei** [comment]
I'm moving this discussion to issue https://github.com/swcarpentry-ja/i18n/issues/21#issue-377677049

**Pull request merged**
